const jargon = [
  ["Bandwidth", "Capacity"],
  ["Bleeding edge", "New or innovative feature"],
  ["Blue sky thinking", "Brainstorm without limits"],
  ["Boil the ocean", "Trying to accomplish too much"],
  ["Circle back", "Revisit"],
  ["Deep dive", "Examine"],
  ["Due Diligence", "Research"],
  ["Empower", "Give authority or agency"],
  ["First and foremost", "Use one word or the other (it's repetitive)"],
  ["Fully baked", "Completely thought through"],
  ["Gain traction", "Move toward the desired goal"],
  ["Game changer", "New event, idea, process"],
  ["Get our ducks in a row", "Have everything completed"],
  ["Giving 110%", "Do your best work"],
  ["Heavy lifting", "Difficult duty or task"],
  ["I'll ping you", "I'll follow up"],
  ["Irregardless", "It's not even a word"],
  ["Leverage", "Use"],
  ["Lipstick on a pig", "Make this situation look better"],
  ["Lots of moving parts", "Complex situation with changing details"],
  ["Low-hanging fruit", "Let's start with the easy tasks first"],
  ["Magic bullet", "Solution to a complex problem"],
  ["Mission-critical", ""],
  ["Move the needle", "Make progress"],
  ["New normal", "New conditions, environment, expectation"],
  ["Open the kimono", "Share information"],
  ["Paradigm shift", "Think about this differently"],
  ["Parking lot issue", "Items to discuss later"],
  ["Pivot", "Change directions"],
  ["Pull the trigger", "Take action"],
  ["Put a pin in it", "Save it for later"],
  ["Raise the bar", "Improve"],
  ["Reinvent the wheel", "Change the process"],
  ["Run it up the flagpole", "Ask management or leadership"],
  ["Strategic partnership", "partnership"],
  ["Synergy", "Collaboration"],
  ["Think outside the box", "New idea or thought"],
  ["Thinking outside the box", "New idea or thought"],
  ["Thought leader", "Expert or authority"],
  ["Top of mind", "Most important idea or thought"],
  ["Win-win", "Good for both parties"],
];

export default jargon;
